### ISSUE TITLE
Include source code of other methods

### ISSUE THREAD

**Issue by pagutierrez** [ayrna/orca#2]
- [ ] NNOP (java)
- [ ] NNPOM (java)
- [ ] GPOR (bash script)

**Comment by BigDataLearning** [comment]
Hi, pagutierrez 

I am planing to carry out my experiments based on your codes. But I haven't found  these three algorithm codes(NNOP, NNPOM, GPOR) here. Can you sent them to me?  My Email is huadw2012@163.com
I sincerely appreciate your help, hope to hear from you soon. 

Best
Huadong

**Comment by zhutuanfei** [comment]
hello, javism, there are some problems when i use orca-master in matlab. I tried to compile libsvm-rank-2.81, SVOREX and SVORIM by running their corresponding "make.m", but all of them failed(my matlab's version is 2013b, and the compiler is "Microsoft Visual Studio 10.0" ).

For libsvm-rank-2.81, many errors occurred in the process of compiling "svmpredict.c". All of them are syntax errors, e.g., missing ":" or undeclared identifiers.

For SVOREX, the error message is listed below:
" C:\PROGRA~1\MATLAB\R2013B\BIN\MEX.PL: Error: Unrecognized switch: -o.
Unable to complete successfully.
Error in make (line 3)
mex CFLAGS="$CFLAGS -std=c99" -largeArrayDims mainSvorex.c alphas.c
cachelist.c datalist.c def_settings.c kcv.c loadfile.c
ordinal_takestep.c setandfi.c smo_kernel.c smo_routine.c smo_settings.c
sm
Error in run (line 63)
evalin('caller', [script ';']);
"

For SVORIM, the error message is described below:
"C:\PROGRA~1\MATLAB\R2013B\BIN\MEX.PL: Error: Unrecognized switch: -o.
Unable to complete successfully.
Error in make (line 3)
mex CFLAGS="$CFLAGS -std=c99 -O3 -fPIC" -largeArrayDims mainSvorim.c
alphas.c cachelist.c datalist.c def_settings.c kcv.c loadfile.c
ordinal_takestep.c setandfi.c smo_kernel.c smo_routine.c smo_set
Error in run (line 63)
evalin('caller', [script ';']);
"

I want to know what causes these problems and how to solve them? Looking forward to your reply. Thank you for your attention.

**Comment by javism** [comment]
We decided not to implement more methods without a matlab/octave interface.

**Comment by pagutierrez** [comment]
Hi huadong2014,
I know it is very late, but we have finally included NNOP and NNPOM methods in ORCA. You can download them and test them. Hope it is useful for you. Please, let us know if you have any problem.
Best regards,
Pedro
