### ISSUE TITLE
Installation under Octave

### ISSUE THREAD

**Issue by fabianp** [ayrna/orca#47]
Hi,

I have Octave installed but when compiling the sources (I'm following the install guide), the Makefile in src/Algorithms assumes that I have Matlab installed, resulting in the following error:

Folder /usr/local/MATLAB/R2017a/ does not exist. Please, set up MATLABDIR propertly
false
Makefile:18: recipe for target '/usr/local/MATLAB/R2017a/' failed
make: *** [/usr/local/MATLAB/R2017a/] Error 1

**Comment by javism** [comment]
Hi Fabian, 
Are you compiling from Octave console or from the Linux shell?

**Comment by fabianp** [comment]
I was using the command line. It works fine if the command is executed from octave-cli. 

I'm closing this issue but I think it would be helpful to specify that the command needs to be run from the octave console in the install guide. Perhaps it is obvious to Octave experienced users, but it was not to me.
