### ISSUE TITLE
Unified experiments ini

### ISSUE THREAD

**Issue by dguijo** [ayrna/orca#62]
Hi! I have been trying to run an unified experiment file (ini format) with a mixture of classifiers (POM, KDLOR) and I always get the same error:

```>> Utilities.runExperiments('config-files/script.ini')
Setting up experiments...
Running experiment exp-kdlor-amae-tormentas-1.ini
Running experiment exp-pom-tormentas-1.ini
error: Error 'C' is not a recognized class parameter name
error: called from
    paramopt>checkParameters at line 135 column 9
    paramopt at line 28 column 1
    crossValideParams at line 180 column 22
    run at line 68 column 26
    launch at line 55 column 13
    runExperiments at line 90 column 25
```

This is the configuration file:
```
[pom]
{general-conf}
seed = 1
basedir = ../exampledata/1-holdout/
datasets = tormentas
standarize = true

{algorithm-parameters}
algorithm = POM

[kdlor-amae]
{general-conf}
seed = 1
basedir = ../exampledata/1-holdout/
datasets = tormentas
standarize = true
num_folds = 5
cvmetric = amae

{algorithm-parameters}
algorithm = KDLOR
kernelType = rbf

{algorithm-hyper-parameters-to-cv}
C = 10.^(-3:1:3)
k = 10.^(-3:1:3)
u = 0.01,0.001,0.0001,0.00001,0.000001
```

It seems that POM is trying to use the hyper-parameters for KDLOR.

Thanks a lot!

**Comment by javism** [comment]
I fixed this issue with the last commit in develop branch. The example works now.

Tested in Octave and Matlab and with option `report_sum = true/false`. 

Please, let me know if there are further problems to close the issue.

**Comment by javism** [comment]
> I fixed this issue with the last commit in develop branch. The example works now.
> 
> Tested in Octave and Matlab and with option `report_sum = true/false`.
> 
> Please, let me know if there are further problems to close the issue.

Also tested with parallel toolboxes in Octave and Matlab.

**Comment by javism** [comment]
Solved by commit https://github.com/ayrna/orca/commit/78390bac15da8f5edf141aeb1e02311638f00c22
