### ISSUE TITLE
hello,I ask one question

### ISSUE THREAD

**Issue by jxw950605** [ayrna/orca#9]
hello,I am a student,and I run the code of ,but for some dataset , show Matrix dimensions don't agree in Utilities class ,results method:
                       cm = confusionmat(act{h},pred{h});
                        cm_sum = cm_sum + cm;
I find the question is confusionmat function, use it to get cm, the Matrix dimensions  don't agree with cm_sum.
can you give me some advise?

**Comment by javism** [comment]
Hi, 
Without any additional information, I suspect that you can have a imbalanced dataset so that cm_sum and cm can have different dimensions in the absence of one class. 

Can you send us the dataset you are using?

**Comment by jxw950605** [comment]
Thank you for your advise.
your suspection is right, and I have solved the question,yes,the problem is from imbalanced dataset, The dataset  was divided into imbalanced train set and test set. 

Thanks again.

**Comment by javism** [comment]
I think we should stop the program @mperezortiz with 'error()' or something like that. 

In the meanwhile I have added some information to the tutorial https://github.com/ayrna/orca/commit/5a0150d23d7ef182df4442035467185a270f3d83

**Comment by jxw950605** [comment]
Thank you very much, it's great.

**Comment by jxw950605** [comment]
@javism Hi~，About the same problem，how can I divide the data set to avoid the imbalanced dataset?
in the past few days, I encountered the problem with the use of other data sets, however, I would like to completely solve it. Can your give some advise? 
thank~

**Comment by javism** [comment]
If your dataset is extremelly imbalanced try to use a hold-out procedure (70% train-30% test or similar setup) instead of a stratified 10-fold. (90%-10% maintaining the class proportion in train and test). You will have more chances to have the minority class both in train and test sets. 

Please, consider that sometimes you will have to think about mixting small classes (example grades 1, 2, 3, 4, 5 with few patterns in 5 suggest to mix classes 4 and 5 depending on the problem). 

Since you don't provide additional information (number of patterns, num. of classes and class frequency) I cannot provide further suggestions. 

best

**Comment by jxw950605** [comment]
Our data is large-scaled and converted through regression datasets by equal-frequency-bin. The number of instance over 200,000(70% train-30% test).

**Comment by jxw950605** [comment]
@javism we think the divided data is balanced, but also failed.

**Comment by javism** [comment]
What about the class distribution? 

You can get the class distribution with 
`freq=hist(train.targets, unique(train.targets))`

**Comment by jxw950605** [comment]
This is the distribution of one of our data
freq=hist(y, unique(y))
freq =

       34874       35498       34891       34907       34805

**Comment by javism** [comment]
There you don't have imbalance problem. Are you using stratified partitions with cvpartition or similar? https://es.mathworks.com/help/stats/cvpartition.html

**Comment by jxw950605** [comment]
thank you for your advise. I found out where the problem. Thanks~
